### ISSUE TITLE
There is no Hobby-Plan on Heroku anymore

### ISSUE THREAD

**Issue by Yeeb1** [Propolisa/Seven#29]
The Hobby-Plan on Heroku has been discontinued and build will fail, because the app.js points to an invalid deployment plan.

**Comment by Acters** [comment]
Hello Yeeb, is the essential plan ( https://devcenter.heroku.com/articles/postgres-essential-tier ) a good solution for you? 
changing heroku-postgresql:hobby-dev in app.json with heroku-postgresql:essential-0
The other semi equivalent plan would be mini: heroku-postgresql:mini

**Comment by Yeeb1** [comment]
Yep thank you
